CupsApp/Models/Country.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CupsApp.Models
{
    public class Country
    {
        [Key]
        public int CountryId { get; set; }
        public string CountryName { get; set; }

        public virtual ICollection<Cup> Cups { get; set; }
    }
}

CupsApp/Models/Cup.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CupsApp.Models
{
    public enum CupType
    {
        tea, coffee
    }
    public class Cup
    {
        [Key]
        public int CupId { get; set; }
        [Required]
        [Range(0.1, 2.0)]
        public double Capacity { get; set; }
        [Required]
        public CupType CupType { get; set; }
        [Required]
        public int CountryID { get; set; }
        public virtual CupImage CupImage { get; set; }
        public virtual Country Country { get; set; }
        [NotMapped]
        public string ImagePath { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
        public Cup()
        {
            ImagePath = "~/AppFiles/Images/default.png";
        }

    }
}

CupsApp/Models/CupImage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CupsApp.Models
{
    public class CupImage
    {
        [Key]
        [ForeignKey("Cup")]
        public int CupImageID { get; set; }
        public byte[] Image { get; set; }
        public virtual Cup Cup { get; set; }

        //[DisplayName("Image")]
        //public string ImagePath { get; set; }

        //public CupImage()
        //{
        //    ImagePath = "~/AppFiles/Images/default.png";
        //}
    }
}

CupsApp/Controllers/CupsController.cs
using CupsApp.Context;
using CupsApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CupsApp.Controllers
{
    public class CupsController : Controller
    {
        // GET: Cups
        private CupContext db = new CupContext();
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ViewAll()
        {
            return View(GetAllCups());
        }
        IEnumerable<Cup> GetAllCups()
        {
             return db.Cups.ToList<Cup>();
        }
        
        public ActionResult AddOrEdit(int? id)
    {
            Cup c = new Cup();
            //Country ca = db.Cups.Where(x => x.CupId == id).FirstOrDefault<Cup>())
            SelectList items;
            if (id != null)
            {
                c = db.Cups.Find(id);

            }
            ViewBag.CountryID = items = new SelectList(db.Countries, "CountryId", "CountryName", c.CountryID);
            return View(c);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOrEdit([Bind(Include = "CupId,Capacity,CupType,CountryID,ImagePath,ImageUpload")]Cup cup)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ///var c = db.Cups.Where(x => x.CupId == cup.CupId).FirstOrDefault<Cup>();
                    if (cup.CupId == 0)
                    {
                        db.Cups.Add(cup);
                        db.SaveChanges();
                        if (cup.ImageUpload != null)
                        {
                            CupImage cupImg = new CupImage();
                            cupImg.CupImageID = cup.CupId;
                            cupImg.Image = new byte[cup.ImageUpload.ContentLength];
                            cup.ImageUpload.InputStream.Read(cupImg.Image, 0, cup.ImageUpload.ContentLength);
                          
                            cupImg.Cup = cup;
                            db.CupImages.Add(cupImg);
                            db.SaveChanges();
                        }
                    }
                    else
                    {
                        if (cup.ImageUpload != null)
                        {
                            var cupImg = db.CupImages.Find(cup.CupId);
                            if (cupImg != null)
                            {
                                cupImg.Image = new byte[cup.ImageUpload.ContentLength];
                                cup.ImageUpload.InputStream.Read(cupImg.Image, 0, cup.ImageUpload.ContentLength);
                                db.Entry(cupImg).State = EntityState.Modified;
                                db.SaveChanges();
                            }

                        }
                        db.Entry(cup).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                }
                ViewBag.CountryID = new SelectList(db.Countries, "CountryId", "CountryName", cup.CountryID);
                return RedirectToAction("Index");
                //return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "ViewAll", GetAllCups()), message = "Operation was Successfully" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                var cupImg = db.CupImages.Find(id);
                var c = db.Cups.Where(x => x.CupId == id).FirstOrDefault<Cup>();
                if(cupImg!=null) db.CupImages.Remove(cupImg);
                db.Cups.Remove(c);
                db.SaveChanges();
                return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "ViewAll", GetAllCups()), message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult GetImage(int id)
        {
            CupImage c = db.CupImages.FirstOrDefault(d => d.CupImageID == id);
            if (c != null &&  c.Image != null) return File(c.Image, "image/png");
            return View();
        }
    }
}

CupsApp/Views/Cups/AddOrEdit.cshtml
@model CupsApp.Models.Cup

@{
    ViewBag.Title = "AddOrEdit";
    Layout = null;
}

@using (Html.BeginForm("AddOrEdit", "Cups", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return jQuaryAjaxPost(this);", data_restUrl=Url.Action("AddOrEdit","Cups", new { id = 0 }) }))
{

    <div class="row">
        @Html.AntiForgeryToken()
            <hr />
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.CupId)

                <div class="form-group">
                    @Html.LabelFor(model => model.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CupType, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.CupType, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CupType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CountryID, "CountryID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("CountryID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CountryID, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ImagePath, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @if (Model.CupId != 0)
                        {
                        <img src="@Url.Action("GetImage", new { id = Model.CupId})" style="margin:10px" height="200" width="200" id="imagePreview"/>
                        }
                            @if (Model.CupId == 0)
                        {
                        <img src="@Url.Content(Model.ImagePath)" style="margin:10px" height="200" width="200" id="imagePreview" />
                        }

                            <input type="file" name="ImageUpload" accept="image/jpeg, image/png" onchange="ShowImagePreview(this,document.getElementById('imagePreview'))" />
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                        @if (Model.CupId != 0)
            {
                <a class="btn btn-success" onclick="refreshAddNewTab('@Url.Action("AddOrEdit","Cups",new{id=0})',false)"><i class="fa fa-plus"></i> Add New</a>
        }
                    </div>
                </div>
            </div>
    </div>
}

CupsApp/Views/Cups/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<ul class="nav nav-tabs">
    <li><a data-toggle="tab" href="#firstTab">View All</a></li>
    <li class="active"><a data-toggle="tab" href="#secondTab">Add New</a></li>
</ul>
<div class="tab-content">
    <div id="firstTab" class="tab-pane fade in">@Html.Action("ViewAll")</div>
    <div id="secondTab" class="tab-pane fade in active">@Html.Action("AddOrEdit")</div>
</div>

<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>


    <script>
        function activatejQueryTable() {
            $("#cupTable").DataTable();
        }

        $(function () {
            activatejQueryTable();
        });

    </script>
}

CupsApp/Views/Cups/ViewAll.cshtml
@model IEnumerable<CupsApp.Models.Cup>

@{
    ViewBag.Title = "ViewAll";
    Layout = null;
}


<table class="table table-striped table-condensed" id="cupTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Capacity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CupType)
        </th>
        <th> @Html.DisplayNameFor(model => model.Country) </th>
        <th> Image </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Capacity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CupType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country.CountryName)
            </td>
            <td> <img id="myimage" src="@Url.Action("GetImage", new { id = item.CupId})" width="100" height="70"  /></td>
            <td>
                <a class="btn btn-primary btn-sm" onclick="Edit('@Url.Action("AddOrEdit", "Cups", new { id = @item.CupId })')"><i class="fa fa-pencil fa-lg"></i></a>
                <a class="btn btn-danger btn-sm" onclick="Delete('@Url.Action("Delete", "Cups", new { id = @item.CupId })')"><i class="fa fa-trash fa-lg"></i></a>
            </td>
        </tr>
    }

</table>

CupsApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cups View", "Index", "Cups", null, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cups View ASP.NET CRUD</p>
        </footer>
    </div>

    @*<div class="loaderbody" id="loaderbody">
        <div class="loader"></div>
    </div>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/Scripts.js"></script>
    <script src="~/Scripts/notify.min.js"></script>
</body>
</html>